### ISSUE TITLE
@findify/analytics: required properties in config

### ISSUE THREAD

**Issue by simonlovesyou** [findify/findify-js#888]
In your own example the only thing you need to initialize the findify analytics client is the findify key

https://github.com/findify/findify-js/blob/develop/packages/analytics/README.md?plain=1#L133 

But when you try to follow this example with typescript it complains about missing properties:

```
Argument of type '{ key: string; }' is not assignable to parameter of type 'Config | (() => void)'.
  Type '{ key: string; }' is missing the following properties from type 'Config': events, platform    ts(2345)
```

# Suggested fix

Make `events` & `platform` optional 

https://github.com/findify/findify-js/blob/develop/packages/analytics/src/types.ts#L8-L13

**Comment by wolff95** [comment]
Hi @simonlovesyou 

I have read what analytics package initialization does with platform and events.

Regarding platform it is important for us to specify it, it is needed as there are particular event setting set for specific platforms, so rather than saying to the specific platform user that they need to add the platform to correctly use it, it is much better to ask everybody to specify the platform. Anyway, this one surely won't be a game changer on your side.

Regarding events, here it got a bit more complicated as to understand this I had to understand what it does now with what the reason might have been between 2 years and 5 years ago. And at the end you are right, it can be optional.
events is an object that main usage is for merchants that wishes to not emit certain events for whatever reason.

To solve your type error, I would suggest you to simply use
`findifyAnalytics({ key: 'your_api_key', events: {}, platform: 'your platform' })`

I have already pushed the optional for events but I will deploy it whenever it comes the urgency to do so.
